<?php

/**
 * @file
 * Code for the Productivity Login feature.
 *
 * Provides GitHub-based OAuth login for Drupal.
 */

include_once 'productivity_login.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Appends the GitHub connect to login form.
 */
function productivity_github_form_user_login_alter(&$form, $form_state) {
  $block = module_invoke('openid_connect', 'block_view', 'openid_connect_login');
  $form['#suffix'] = drupal_render($block['content']);
}

