<?php

// Plugin definition
$plugin = array(
  'title' => t('User'),
  'category' => t('Productivity'),
  'icon' => 'user.png',
  'theme' => 'user',
  'regions' => array(
    'top' => t('Top'),
    'bottom-right' => t('Bottom Right'),
    'bottom-left' => t('Bottom Left'),
    'attendance' => t('Attendance'),
    'attendance-right' => t('Attendance Right'),
    'attendance-left' => t('Attendance Left'),
    'tracking' => t('Tracking'),
    'totals-right' => t('Totals Right'),
    'totals-left' => t('Totals Left'),
  ),
);
